units:
  p: u + 2
  pp: U + 2
  op: u + 6
  stlp: U + 10
points:
  zones:
    matrixl:
      anchor:
        shift: [27, -175]
      #key:
      #  padding: U
      #  spread: U
      columns:
        outer:
          rows:
            bottom:
              #shift: [U/2, 0]
              width: 2u
            home.width: 2U
            top.width: 2U
            #num.shift: [-U/2, 0]
        pinky:
          rows:
            bottom.shift: [U/2, 0]
            num.shift: [-U/2, 0]
            func.skip: true
        ring:
          rows:
            bottom.shift: [U/2, 0]
            num.shift: [-U/2, 0]
        middle:
          rows:
            bottom.shift: [U/2, 0]
            num.shift: [-U/2, 0]
        index:
          rows:
            mod:
              shift: [U, 0]
              width: 3u
            bottom.shift: [-U/2, 0]
            num.shift: [-U/2, 0]
        inner:
          rows:
            mod.skip: true
            bottom.shift: [U/2, 0]
            num.shift: [-U/2, 0]
      rows:
        mod:
        bottom:
        home:
        top:
        num:
        func:
    matrixr:
      anchor:
        ref: matrixl_inner_mod
        shift: [3.25U, 0]
      columns:
        inner:
          rows.mod:
            width: 3u
        index:
          rows.mod.skip: true
        middle:
          rows.mod.skip: true
        ring:
          rows.mod.shift: [-U, 0]
          rows.bottom.shift: [U/2, 0]
        pinky:
          rows.mod.shift: [-U, 0]
          rows.bottom.shift: [U/2, 0]
          rows.func.skip: true
        outer:
          rows.mod.shift: [-U, 0]
          rows.bottom:
            shift: [U, 0]
            width: 2u
          rows.home.shift: [-U/2, 0]
        outer2:
          rows.mod.shift: [-U, 0]
          rows.bottom.skip: true
          rows.home:
            shift: [1.5U, 0]
            width: 2u
          rows.top.shift: [-U/2, 0]
        outer3:
          rows.mod.skip: true
          rows.bottom.skip: true
          rows.home.skip: true
          rows.num:
            shift: [U/2, 0]
            width: 2u
          rows.func:
            shift: [-U, 0]
        outer4:
          rows.mod.skip: true
          rows.bottom.skip: true
          rows.home.skip: true
          rows.top.skip: true
          rows.num.skip: true
      rows:
        mod:
        bottom:
          shift: [-U/2, 0]
        home:
        top:
        num:
        func:
          shift: [-U/2, 0]
    arrows:
      anchor:
        ref: matrixr_inner_mod
        shift: [7.8U, 0.1U]
        rotate: 45
      columns:
        left:
        right:
      rows:
        bottom:
        top:
    pages:
      anchor:
        ref: arrows_right_bottom
        shift: [1.35U, -0.7U]
      columns:
        left:
        right:
      rows:
        bottom:
        top:
    special:
      anchor:
        ref: matrixr_outer4_num
        shift: [1.5U, 0U]
      columns:
        left:
        mid:
        right:
      rows:
        bottom:
        top:
outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [pp, pp]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [u-0.5,u-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrixl_outer_func
          shift: [-0.5op, 0.5op]
        - ref: special_right_top
          shift: [0.5op, 0.5op]
        - ref: pages_right_bottom
          shift: [0.5op, -0.5op]
        - ref: pages_left_bottom
          shift: [-0.5op, -0.5op]
        #- ref: arrows_right_bottom
        #  shift: [0.5op, -0.5op]
        - ref: arrows_left_bottom
          shift: [-0.5op, -0.5op]
        - ref: matrixr_outer2_mod
          shift: [0.5op, -0.5op]
        - ref: matrixl_outer_mod
          shift: [-0.5op, -0.5op]
      fillet: 2
  board3d:
    - what: polygon
      operation: stack
      points:
        - ref: matrixl_outer_func
          shift: [-0.5stlp, 0.5stlp]
        - ref: special_right_top
          shift: [0.5stlp, 0.5stlp]
        - ref: pages_right_bottom
          shift: [0.5stlp, -0.5stlp]
        - ref: pages_left_bottom
          shift: [-0.5stlp, -0.5stlp]
        #- ref: arrows_right_bottom
        #  shift: [0.5stlp, -0.5stlp]
        - ref: arrows_left_bottom
          shift: [-0.5stlp, -0.5stlp]
        - ref: matrixr_outer2_mod
          shift: [0.5stlp, -0.5stlp]
        - ref: matrixl_outer_mod
          shift: [-0.5stlp, -0.5stlp]
      fillet: 2
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  tutorial:
    outlines:
      main:
        outline: board
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref.aggregate.parts: [matrixl_inner_func, matrixr_inner_func]
          shift: [0,-7.25]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref.aggregate.parts: [matrixr_outer4_func, special_left_top]
          shift: [0, 0]
          rotate: -45
      scrollwheel:
        what: scrollwheel
        params:
          from: GND
          to: GND
          A: GND
          B: GND
          C: GND
          D: GND
        where:
          ref.aggregate.parts: [matrixl_inner_top, matrixr_inner_top]
          shift: [0, 0]
      rotary:
        what: rotary
        params:
          from: GND
          to: GND
          A: GND
          B: GND
          C: GND
        where:
          ref.aggregate.parts: [matrixl_inner_bottom, matrixr_inner_bottom]
          shift: [0, 0]
          rotate: -90
      holeTopLeft:
        what: mountinghole
        where:
          ref.aggregate.parts: [matrixl_outer_func, matrixl_ring_func]
          shift: [0, 0.3u]
      holeTopRight:
        what: mountinghole
        where:
          ref.aggregate.parts: [special_mid_top, special_right_top]
          shift: [0, -u/2]
      holeBottomRight:
        what: mountinghole
        where:
          ref.aggregate.parts: [matrixr_outer2_mod, arrows_left_bottom]
          shift: [0, -0.3u]
      holeBottomLeft:
        what: mountinghole
        where:
          ref.aggregate.parts: [matrixl_outer_bottom, matrixl_pinky_bottom]
          shift: [0, -0.3u]
cases:
  bottom:
    - name: board3d
      extrude: 1