meta:
  engine: 4.0.5
  name: "travis_keytest"
  version: &meta_version "2024.03.21"
  date: "2024-03-21"
  author: '"Travis Hardiman"'
  url: https://github.com/dieseltravis/travis-ergogen-2024/keytest
units:
points:
  zones:
    single:
      anchor:
        shift: [100, -100]
        rotate: 45
      key:
        padding: U
        spread: U
        tags: 
          - key
      columns:
        A:
          key:
            column_net: col0
          rows:
            one:
              row_net: row0
              key:
                led_next: LED_0
                led_this: LED_1
              width: 1.0U
      rows:
        one:
          tags: 
            - row_odd
  rotate: 0
outlines:
  _raw:
    - what: rectangle
      where: true
      bound: true
      size: [U + 2, U + 2]
  _keys:
    - what: rectangle
      where: true
      bound: false
      size: [U - 0.5, U - 0.5]
  _board:
    - what: polygon
      operation: stack
      points:
        # top left
        - ref: single_A_one
          shift: [-1U, 1U]
        # top right
        - ref: single_A_one
          shift: [1U, 1U]
        # bottom right
        - ref: single_A_one
          shift: [1U, -1U]
        # bottom left
        - ref: single_A_one
          shift: [-1U, -1U]
      fillet: 3
  _combo:
    - name: _board
    - operation: subtract
      name: _keys
pcbs:
  travis_keytest:
    outlines:
      main:
        outline: _board
    footprints:
      keymod:
        what: custom/key-module
        where: true
        params:
          U: U
          name: "{{name}}"
          colnet: "{{column_net}}"
          rownet: "{{row_net}}"
          led_this: "{{key.led_this}}"
          led_next: "{{key.led_next}}"
    references: true
